# Header
menu:
  主页: /
  所有文章: /archives
  爬坑日记: /pitdiary
  关于: /about
  #相册: /instagram

#####
# SubNav
subnav:
  github: "https://github.com/Raineye"
  weibo: "http://weibo.com/2940899633/profile?topnav=1&wvr=6&is_all=1"
  # rss: /atom.xml
  zhihu: "https://www.zhihu.com/people/xue-bing-9"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: http://7xpp66.com1.z0.glb.clouddn.com/blog/img/20150718184411_uKcTn.thumb.700_0.jpeg

#你的头像url
avatar: http://7xpp66.com1.z0.glb.clouddn.com/blog/img/20150718184411_uKcTn.thumb.700_0.jpeg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: rainey
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
friends:
  Season's neko: http://xnix.me/
  Nick's Blog: http://nick930826.github.io/


#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 宁波大学科学技术学院12级，现就职于三江购物俱乐部股份有限公司。一个严重的强迫症后期患者。
